config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get "/message", to: 'static_pages#message'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :artists
  resources :lives, only: [:new, :create, :destroy]
  resources :notifications, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :artist
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    @notification.artist_id = current_user.artist.id
    if @notification.save
      redirect_to root_url
    else
      flash[:danger] = "失敗しました"
      logger.error @live.errors.full_messages.join(", ")  # エラー内容をログに出力
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

    def notification_params
      params.require(:notification).permit(:message)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/new.html.erb
<% provide(:title, "フォロワーにメッセージを送信する") %>
<div class="row content">
	<div class="col-md-6 offset-md-3 sign-up-form">
		<%= form_with(model: @notification, url: notifications_path) do |f| %>
			
			<%= f.label :message, "内容" %>
			<%= f.text_area :message, class: "form-control", rows: 10 %>

			<%= f.submit "送信", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>