config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get "/message", to: 'static_pages#message'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :artists
  resources :lives, only: [:new, :create, :destroy]
  resources :notifications, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header>
  <div class="header">
    <nav class="navbar navbar-expand-lg bg-dark">
      <div class="container">
        <a class="navbar-brand text-white" href="/"><i class="fa-light fa-headphones-simple"></i>Livespot</a>
        <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "ホーム", root_path, class: "nav-link active" %>
            </li>
            <% if logged_in? && current_user.is_artist == false %>
            <li class="nav-item">
              <%= link_to "メッセージ", message_path, class: "nav-link" %>
            </li>
            <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                設定
              </a>
              <% if logged_in? %>
                <ul class="dropdown-menu">
                  <% if current_user.is_artist == true %>
                    <li><%= link_to "ライブを開催する", new_life_path, class: "dropdown-item" %></li>
                    <li><%= link_to "告知", new_notification_path, class: "dropdown-item" %></li>
                  <% end %>
                  <li><%= link_to "プロフィール", user_path(current_user), class: "dropdown-item" %></li>
                  <li><%= link_to "ユーザー設定", edit_user_path(current_user), class: "dropdown-item" %></li>
                  <li><%= link_to "ログアウト", logout_path, class: "dropdown-item", data: { "turbo-method": :delete } %></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="#">その他</a></li>
                </ul>
              <% else %>
                <ul class="dropdown-menu">
                  <li><%= link_to "無料会員登録", new_user_path, class: "dropdown-item" %></li>
                  <li><%= link_to "ログイン", login_path, class: "dropdown-item" %></li>
                </ul>
              <% end %>
            </li>
          </ul>
          <form id="location-search-form" class="d-flex" role="search">
            <input id="location-input" class="form-control me-2" type="search" placeholder="地名やアーティスト名" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">search</button>
          </form>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> flash-content"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>

</html>